export const teammates = [
  {
    id: 'mira',
    name: 'Mira Khan',
    role: 'Account Lead',
    initials: 'MK',
    color: '#f97316',
    capacity: 8,
  },
  {
    id: 'ray',
    name: 'Ray Ahmed',
    role: 'Creative Director',
    initials: 'RA',
    color: '#2563eb',
    capacity: 7,
  },
  {
    id: 'nora',
    name: 'Nora Islam',
    role: 'Performance Marketer',
    initials: 'NI',
    color: '#16a34a',
    capacity: 6,
  },
  {
    id: 'sami',
    name: 'Sami Rahman',
    role: 'Designer',
    initials: 'SR',
    color: '#9333ea',
    capacity: 6,
  },
  {
    id: 'tania',
    name: 'Tania Chowdhury',
    role: 'Content Strategist',
    initials: 'TC',
    color: '#dc2626',
    capacity: 5,
  },
]

export const projects = [
  {
    id: 'brand-sprint',
    name: 'Brand Sprint',
    client: 'Northstar Studio',
    color: '#f97316',
    owner: 'mira',
    due: '2026-06-17',
    health: 'On track',
    brief: 'Identity refresh, campaign launch plan, and approval workflow.',
  },
  {
    id: 'growth-retainer',
    name: 'Growth Retainer',
    client: 'Bloommerce',
    color: '#2563eb',
    owner: 'nora',
    due: '2026-06-28',
    health: 'At risk',
    brief: 'Paid acquisition, weekly creative tests, reporting, and landing pages.',
  },
  {
    id: 'content-engine',
    name: 'Content Engine',
    client: 'Cedar Labs',
    color: '#16a34a',
    owner: 'tania',
    due: '2026-07-04',
    health: 'On track',
    brief: 'Editorial calendar, subject-matter interviews, and gated assets.',
  },
]

export const statuses = [
  {
    id: 'backlog',
    name: 'Backlog',
    description: 'Ideas, requests, and scoped work waiting for kickoff.',
  },
  {
    id: 'todo',
    name: 'To do',
    description: 'Ready work for this sprint.',
  },
  {
    id: 'doing',
    name: 'Doing',
    description: 'Active tasks with owners and due dates.',
  },
  {
    id: 'review',
    name: 'Review',
    description: 'Client, QA, or internal approval.',
  },
  {
    id: 'done',
    name: 'Done',
    description: 'Completed and archived for reporting.',
  },
]

export const initialTasks = [
  {
    id: 'task-101',
    projectId: 'brand-sprint',
    title: 'Finalize discovery notes into creative brief',
    status: 'done',
    priority: 'High',
    assignee: 'mira',
    collaborators: ['ray', 'tania'],
    due: '2026-06-04',
    start: '2026-06-01',
    estimate: 4,
    tags: ['Brief', 'Strategy'],
    progress: 100,
    description:
      'Turn call notes, competitor review, and positioning decisions into a client-ready creative brief.',
    subtasks: [
      { id: 'st-1', label: 'Collect client inputs', done: true },
      { id: 'st-2', label: 'Summarize target audience', done: true },
      { id: 'st-3', label: 'Share brief for approval', done: true },
    ],
    comments: [
      {
        id: 'c-1',
        author: 'ray',
        text: 'Added the competitive frame to the deck.',
        time: 'Yesterday',
      },
    ],
  },
  {
    id: 'task-102',
    projectId: 'brand-sprint',
    title: 'Moodboard routes for visual direction',
    status: 'doing',
    priority: 'High',
    assignee: 'sami',
    collaborators: ['ray'],
    due: '2026-06-07',
    start: '2026-06-03',
    estimate: 8,
    tags: ['Design', 'Creative'],
    progress: 58,
    description:
      'Create three distinct visual routes with typography, palette, references, and rollout notes.',
    subtasks: [
      { id: 'st-4', label: 'Route A: editorial', done: true },
      { id: 'st-5', label: 'Route B: modern utility', done: true },
      { id: 'st-6', label: 'Route C: premium warmth', done: false },
    ],
    comments: [
      {
        id: 'c-2',
        author: 'mira',
        text: 'Client prefers less formal typography. Keep that in route C.',
        time: 'Today',
      },
    ],
  },
  {
    id: 'task-103',
    projectId: 'brand-sprint',
    title: 'Client presentation rehearsal',
    status: 'todo',
    priority: 'Medium',
    assignee: 'ray',
    collaborators: ['mira', 'sami'],
    due: '2026-06-10',
    start: '2026-06-09',
    estimate: 2,
    tags: ['Meeting'],
    progress: 0,
    description:
      'Run through timing, speaker notes, objections, and next-step asks before the client meeting.',
    subtasks: [
      { id: 'st-7', label: 'Prepare talking points', done: false },
      { id: 'st-8', label: 'Record rehearsal notes', done: false },
    ],
    comments: [],
  },
  {
    id: 'task-104',
    projectId: 'brand-sprint',
    title: 'Logo lockup refinement',
    status: 'review',
    priority: 'Medium',
    assignee: 'sami',
    collaborators: ['ray'],
    due: '2026-06-12',
    start: '2026-06-08',
    estimate: 6,
    tags: ['Design', 'Approval'],
    progress: 75,
    description:
      'Refine selected logo direction, spacing rules, small-size use cases, and monochrome lockups.',
    subtasks: [
      { id: 'st-9', label: 'Small-size tests', done: true },
      { id: 'st-10', label: 'Export review board', done: false },
    ],
    comments: [
      {
        id: 'c-3',
        author: 'ray',
        text: 'Spacing looks right. Need one more black-and-white proof.',
        time: '2h ago',
      },
    ],
  },
  {
    id: 'task-201',
    projectId: 'growth-retainer',
    title: 'Paid social testing matrix',
    status: 'doing',
    priority: 'High',
    assignee: 'nora',
    collaborators: ['sami'],
    due: '2026-06-06',
    start: '2026-06-02',
    estimate: 5,
    tags: ['Performance', 'Ads'],
    progress: 64,
    description:
      'Build weekly creative test matrix with audience, offer, hook, placement, and success metric.',
    subtasks: [
      { id: 'st-11', label: 'Audit previous winners', done: true },
      { id: 'st-12', label: 'Define first 12 tests', done: true },
      { id: 'st-13', label: 'Confirm measurement plan', done: false },
    ],
    comments: [],
  },
  {
    id: 'task-202',
    projectId: 'growth-retainer',
    title: 'Landing page wireframe',
    status: 'todo',
    priority: 'High',
    assignee: 'sami',
    collaborators: ['nora', 'ray'],
    due: '2026-06-11',
    start: '2026-06-05',
    estimate: 7,
    tags: ['Web', 'Conversion'],
    progress: 18,
    description:
      'Create above-the-fold variants, pricing proof points, comparison block, and form behavior.',
    subtasks: [
      { id: 'st-14', label: 'Draft conversion hierarchy', done: true },
      { id: 'st-15', label: 'Wireframe desktop', done: false },
      { id: 'st-16', label: 'Wireframe mobile', done: false },
    ],
    comments: [
      {
        id: 'c-4',
        author: 'nora',
        text: 'Please keep the demo form short. Fewer fields performed better.',
        time: 'Today',
      },
    ],
  },
  {
    id: 'task-203',
    projectId: 'growth-retainer',
    title: 'Weekly performance report',
    status: 'backlog',
    priority: 'Low',
    assignee: 'nora',
    collaborators: ['mira'],
    due: '2026-06-14',
    start: '2026-06-12',
    estimate: 3,
    tags: ['Reporting'],
    progress: 0,
    description:
      'Summarize CPA, ROAS, spend pacing, winning creatives, and next week experiments.',
    subtasks: [
      { id: 'st-17', label: 'Pull channel data', done: false },
      { id: 'st-18', label: 'Write recommendations', done: false },
    ],
    comments: [],
  },
  {
    id: 'task-301',
    projectId: 'content-engine',
    title: 'June editorial calendar',
    status: 'review',
    priority: 'Medium',
    assignee: 'tania',
    collaborators: ['mira'],
    due: '2026-06-05',
    start: '2026-06-01',
    estimate: 4,
    tags: ['Content', 'Planning'],
    progress: 80,
    description:
      'Map weekly topics, writer owners, review dates, distribution hooks, and promotion assets.',
    subtasks: [
      { id: 'st-19', label: 'Topic map', done: true },
      { id: 'st-20', label: 'Distribution hooks', done: true },
      { id: 'st-21', label: 'Client approval', done: false },
    ],
    comments: [
      {
        id: 'c-5',
        author: 'mira',
        text: 'Move the thought-leadership article one week earlier.',
        time: 'Yesterday',
      },
    ],
  },
  {
    id: 'task-302',
    projectId: 'content-engine',
    title: 'Interview subject matter experts',
    status: 'todo',
    priority: 'Medium',
    assignee: 'tania',
    collaborators: ['ray'],
    due: '2026-06-13',
    start: '2026-06-09',
    estimate: 5,
    tags: ['Research'],
    progress: 10,
    description:
      'Schedule and run three expert interviews for the security trends report.',
    subtasks: [
      { id: 'st-22', label: 'Confirm guest list', done: true },
      { id: 'st-23', label: 'Send questions', done: false },
      { id: 'st-24', label: 'Transcribe calls', done: false },
    ],
    comments: [],
  },
]
